
server:
  servlet:
    context-path: /flowable
  port: 8011

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1/work?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  http:
    converters:
      preferred-json-mapper: jackson
  messages:
    basename: i18n/messages
